### ISSUE TITLE
Unable to build with -Wpedantic -Werror

### ISSUE THREAD

**Issue by AndersHogqvist** [resetius/coroio#37]
When building with -Wpedantic -Werror there are a lot of errors caused by unused variables, unnecessary move operations, comparisons between different types etc etc.

**Comment by resetius** [comment]
https://github.com/resetius/coroio/commit/f5367bb6641214a4b6b8f4716b9228b956b219fb

**Comment by resetius** [comment]
Thank you! Added these options to CMakeLists.txt
